apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp

spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp

  template:
    metadata:
      labels:
        app: myapp

    spec:
      containers:
        - name: myapp-container
          image: yourdockerhubusername/myapp:v1   # 🔥 replace with your Docker Hub username
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort   # ✅ works in local / Jenkins / Minikube

  selector:
    app: myapp

  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007   # ✅ access via this port
